name: Generate Portfolio Banner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-banner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate banner image
      run: python export_readme.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./resource
        publish_branch: gh-pages
        keep_files: false
